import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  container: {
    marginVertical: 20,
  },
  header: {
    marginBottom: 4,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.bgSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  beerIcon: {
    fontSize: 32,
  },
  titleContainer: {
    flex: 1,
    gap: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.platinum,
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.smoke,
    letterSpacing: 0.3,
  },
  headerDivider: {
    height: 2,
    backgroundColor: Colors.bgSecondary,
    borderRadius: 1,
  },
  periodContainer: {
    flexDirection: "row",
    backgroundColor: Colors.bgSecondary,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    marginTop: 0,
  },
  periodTab: {
    flex: 1,
    paddingVertical: 9,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  periodTabActive: {
    backgroundColor: Colors.primaryBlue,
  },
  periodLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.smoke,
    letterSpacing: 0.2,
  },
  periodLabelActive: {
    color: Colors.bg,
    fontWeight: "800",
  },
  filterContainer: {
    paddingVertical: 16,
    gap: 10,
    paddingHorizontal: 4,
  },
  filterPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: Colors.bgSecondary,
  },
  filterPillActive: {
    backgroundColor: Colors.gold,
    borderColor: Colors.gold,
  },
  filterEmoji: {
    fontSize: 18,
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.platinum,
    letterSpacing: 0.3,
  },
  filterLabelActive: {
    color: Colors.bg,
    fontWeight: "800",
  },
  leaderboardList: {
    gap: 12,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: 16,
  },
  emptyIconWrap: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 12,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: Colors.smoke,
    textAlign: "center",
    lineHeight: 20,
  },
  leaderboardItem: {
    backgroundColor: Colors.bgCard,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    gap: 12,
  },
  cardPressable: {
    width: "100%",
  },
  mainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  topThreeItem: {
    borderColor: Colors.gold,
  },
  rankContainer: {
    width: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  medalEmoji: {
    fontSize: 28,
  },
  rankNumber: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.smoke,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  firstPlaceAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: "#FFD700",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  secondPlaceAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: "#C0C0C0",
    shadowColor: "#C0C0C0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  thirdPlaceAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: "#CD7F32",
    shadowColor: "#CD7F32",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  userInfo: {
    flex: 1,
    gap: 4,
  },
  userNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  userName: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.platinum,
  },
  badgesRow: {
    flexDirection: "row",
    gap: 4,
  },
  badge: {
    fontSize: 14,
  },
  clubName: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.smoke,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(57, 243, 255, 0.08)",
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(57, 243, 255, 0.08)",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  statText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.smoke,
  },
  streakEmoji: {
    fontSize: 12,
  },
  beerCountContainer: {
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
    minWidth: 90,
  },
  beerEmoji: {
    fontSize: 20,
  },
  beerCount: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.gold,
  },
  litresLabel: {
    fontSize: 11,
    color: Colors.smoke,
    letterSpacing: 0.6,
  },
});
