import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/ui";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 20,
  },
  fullscreenButtonWrapper: {
    alignItems: "center",
    marginBottom: 12,
  },
  headerIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
  },
  fullscreenHint: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    marginTop: 8,
    opacity: 0.7,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: 4,
    marginBottom: 6,
  },
  headerSubtitle: {
    fontSize: 12,
    letterSpacing: 0.5,
    opacity: 0.7,
  },
  ledDisplay: {
    marginHorizontal: 16,
    marginVertical: 20,
    borderRadius: 20,
    overflow: "hidden",
    height: 200,
    position: "relative",
  },
  ledBorder: {
    flex: 1,
    margin: 4,
    borderWidth: 3,
    borderColor: "#333",
    borderRadius: 16,
    position: "relative",
    overflow: "hidden",
  },
  cornerLight: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    zIndex: 10,
  },
  editHintOverlay: {
    position: "absolute",
    top: 8,
    right: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    zIndex: 5,
  },
  editHintText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    opacity: 0.5,
  },
  textContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 24,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0.3,
    textAlign: "center",
    opacity: 0.7,
  },
  ledText: {
    flex: 1,
    fontWeight: "900",
    fontFamily: "monospace",
    letterSpacing: 4,
  },
  scanlines: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  scanline: {
    height: 2,
    backgroundColor: Colors.platinum,
  },
  quickEditContainer: {
    marginHorizontal: 16,
    marginBottom: 20,
  },
  quickEditInput: {
    borderWidth: 2,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    minHeight: 80,
    maxHeight: 120,
    textAlignVertical: "top",
    backgroundColor: Colors.bgCard,
    marginBottom: 12,
    lineHeight: 24,
    fontWeight: "500",
  },
  quickEditActions: {
    flexDirection: "row",
    gap: 12,
  },
  quickEditButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 6,
    backgroundColor: Colors.bgCard,
  },
  quickEditButtonText: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1,
  },
  controls: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 12,
    marginBottom: 24,
  },
  modeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    paddingVertical: 14,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  modeButtonText: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  waveToggleContainer: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  waveToggleCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  waveToggleContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  waveToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  waveToggleIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  waveToggleLabel: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  waveToggleDesc: {
    fontSize: 11,
    fontWeight: "500",
    opacity: 0.7,
  },
  toggleSwitch: {
    width: 52,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 3,
    justifyContent: "center",
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  toggleThumbActive: {
    transform: [{ translateX: 22 }],
  },
  speedControl: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  speedLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  speedSlider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  speedButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  speedTrack: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.bgCard,
    borderRadius: 3,
    overflow: "hidden",
  },
  speedFill: {
    height: "100%",
    borderRadius: 3,
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 24,
    marginTop: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 2,
    opacity: 0.9,
  },
  sectionHint: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
    opacity: 0.6,
  },
  styleScroll: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
    overflow: "visible",
  },
  styleCard: {
    width: 100,
    marginRight: 12,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  styleIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  styleLabel: {
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 12,
  },
  activeIndicator: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  fontStyleCard: {
    width: 120,
    marginRight: 12,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  fontStylePreview: {
    width: "100%",
    height: 60,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    overflow: "hidden",
  },
  fontStylePreviewText: {
    fontSize: 36,
    fontWeight: "900",
    fontFamily: "monospace",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  fontStyleInfo: {
    gap: 2,
  },
  fontStyleLabel: {
    fontSize: 11,
    fontWeight: "700",
    textAlign: "left",
    letterSpacing: 0.5,
  },
  fontStyleDesc: {
    fontSize: 9,
    fontWeight: "500",
    textAlign: "left",
    opacity: 0.7,
    lineHeight: 11,
  },
  savedMessageItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  savedMessageButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  savedMessageText: {
    flex: 1,
    fontSize: 13,
    color: Colors.platinum,
    fontWeight: "500",
  },
  deleteMessageButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  presetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  presetText: {
    flex: 1,
    fontSize: 13,
    color: Colors.platinum,
    fontWeight: "500",
  },
  fullscreenContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  fullscreenLED: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    overflow: "hidden",
    position: "relative",
  },
  fullscreenHintContainer: {
    position: "absolute",
    bottom: 20,
    alignItems: "center",
  },
  exitHintDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
    opacity: 0.3,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  settingsModal: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingBottom: 40,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 2,
  },
  settingsContent: {
    paddingHorizontal: 20,
  },
  settingSection: {
    marginBottom: 24,
  },
  settingLabel: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  sliderContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sliderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  sliderTrack: {
    flex: 1,
    height: 8,
    backgroundColor: Colors.bgCard,
    borderRadius: 4,
    overflow: "hidden",
  },
  sliderFill: {
    height: "100%",
    borderRadius: 4,
  },
  speedPresets: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  speedPreset: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  speedPresetText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.smoke,
    letterSpacing: 0.5,
  },
  modeToggleContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 12,
  },
  modeToggleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  modeToggleText: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  doneButton: {
    marginHorizontal: 20,
    marginTop: 12,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
  },
  doneButtonText: {
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 2,
  },
  bgColorButton: {
    position: "absolute",
    top: 8,
    left: 26,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    zIndex: 10,
  },
  bgColorSwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
  },
  bgSwatchCard: {
    width: 72,
    height: 90,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    overflow: "hidden",
  },
});
