import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    position: "relative",
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  badge: {
    position: "absolute",
    right: 20,
    top: 20,
    backgroundColor: Colors.gold,
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.bg,
  },
  tabContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57, 243, 255, 0.1)",
  },
  tab: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    position: "relative",
  },
  tabContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tabText: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.smoke,
  },
  tabTextActive: {
    color: Colors.gold,
  },
  tabBadge: {
    backgroundColor: "rgba(57, 243, 255, 0.15)",
    borderRadius: 10,
    minWidth: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  tabBadgeActive: {
    backgroundColor: Colors.gold,
    borderColor: Colors.gold,
  },
  tabBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.gold,
  },
  tabBadgeTextActive: {
    color: Colors.bg,
  },
  tabIndicator: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: Colors.gold,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  requestCard: {
    marginBottom: 16,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.15)",
  },
  cardGradient: {
    padding: 16,
    backgroundColor: Colors.bgCard,
  },
  userSection: {
    flexDirection: "row",
    marginBottom: 12,
  },
  avatarContainer: {
    position: "relative",
    marginRight: 12,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.velvet,
  },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.velvet,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitial: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.platinum,
  },
  onlineBadge: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#10B981",
    borderWidth: 2,
    borderColor: Colors.bg,
  },
  userInfo: {
    flex: 1,
    justifyContent: "center",
  },
  userName: {
    fontSize: 17,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 4,
  },
  clubRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 2,
  },
  clubName: {
    fontSize: 13,
    color: Colors.gold,
    fontWeight: "500",
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 2,
  },
  dateText: {
    fontSize: 12,
    color: Colors.gold,
    fontWeight: "600",
  },
  timeAgo: {
    fontSize: 12,
    color: Colors.smoke,
  },
  message: {
    fontSize: 14,
    color: Colors.smoke,
    fontStyle: "italic",
    lineHeight: 20,
    marginBottom: 16,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
  },
  button: {
    flex: 1,
    borderRadius: 14,
    overflow: "hidden",
  },
  declineButton: {
    backgroundColor: Colors.bgSecondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  declineText: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.lightGrey,
  },
  acceptButtonContainer: {
    flex: 1,
  },
  acceptGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    backgroundColor: Colors.gold,
    borderRadius: 14,
  },
  acceptText: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.bg,
  },
  chatNowButton: {
    flex: 1,
    backgroundColor: "#10B981",
  },
  chatNowGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
  },
  chatNowText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  cancelButton: {
    backgroundColor: Colors.bgSecondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  cancelText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.lightGrey,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 12,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: Colors.smoke,
    textAlign: "center",
    lineHeight: 20,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
  },
  loadingText: {
    fontSize: 15,
    color: Colors.smoke,
  },
});
