import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/ui";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const CARD_WIDTH = SCREEN_WIDTH - 32;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57, 243, 255, 0.1)",
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.gold,
  },
  headerSubtitle: {
    fontSize: 12,
    color: Colors.smoke,
    marginTop: 2,
  },
  headerRight: {
    width: 60,
    alignItems: "flex-end",
  },
  liveIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 59, 48, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  // Sleek Single-Line Filter Bar Styles
  sleekFilterBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57, 243, 255, 0.1)",
    gap: 12,
  },
  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: Colors.bgSecondary,
  },
  dateSelectorText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.platinum,
  },
  verticalDivider: {
    width: 1,
    height: 24,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  activitySelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: Colors.bgSecondary,
  },
  activitySelectorText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.platinum,
  },
  activityEmoji: {
    fontSize: 14,
  },
  viewModeSelector: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: Colors.bgSecondary,
  },
  viewModeSelectorText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.platinum,
  },
  flexSpacer: {
    flex: 1,
  },
  resultCount: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.gold,
  },
  viewModeButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  quickFilters: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57, 243, 255, 0.1)",
  },
  quickFilterButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.15)",
  },
  quickFilterText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.smoke,
  },
  // Compact Date Picker Modal Styles
  datePickerContent: {
    // padding: 20,
  },
  datePickerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.platinum,
    marginBottom: 16,
    textAlign: "center",
  },
  dateGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  dateCard: {
    width: "22%",
    backgroundColor: Colors.bgSecondary,
    borderRadius: 16,
    alignItems: "center",
    height: 80,
    justifyContent: "center",
    gap: 4,
  },
  dateCardActive: {
    backgroundColor: Colors.gold,
  },
  dateCardLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.platinum,
  },
  dateCardLabelActive: {
    color: Colors.bg,
  },
  dateCardDay: {
    fontSize: 11,
    fontWeight: "800",
    color: Colors.lightGrey,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  dateCardDayActive: {
    color: Colors.bg,
  },
  dateCardNumber: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.platinum,
  },
  dateCardNumberActive: {
    color: Colors.bg,
  },
  dateCardCount: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.gold,
    backgroundColor: "rgba(255, 215, 0, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 24,
    textAlign: "center",
  },
  dateCardCountActive: {
    color: Colors.bg,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  // Activity Picker Modal Styles
  activityPickerContent: {
    // padding: 24,
  },
  activityPickerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.platinum,
    marginBottom: 20,
    textAlign: "center",
  },
  activityOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.bgSecondary,
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "transparent",
  },
  activityOptionActive: {
    borderColor: Colors.gold,
  },
  activityOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  activityOptionIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.bgCard,
    borderRadius: 24,
  },
  activityOptionEmoji: {
    fontSize: 24,
  },
  activityOptionTextContainer: {
    flex: 1,
  },
  activityOptionLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 4,
  },
  activityOptionCount: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.smoke,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
  },
  cardSeparator: {
    height: 16,
  },
  paginationFooter: {
    alignItems: "center",
    paddingVertical: 24,
  },
  paginationEnd: {
    fontSize: 13,
    color: Colors.smoke,
    fontWeight: "500",
  },
  card: {
    width: CARD_WIDTH,
    height: 420,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  cardList: {
    height: 280,
  },
  cardPressable: {
    width: "100%",
    height: "100%",
  },
  cardImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    backgroundColor: Colors.bgCard,
    objectFit: "cover",
  },
  avatarFallback: {
    backgroundColor: Colors.velvet,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: {
    fontSize: 80,
    fontWeight: "700",
    color: Colors.gold,
  },
  cardGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  activityBadgeContainer: {
    position: "absolute",
    top: 16,
    left: 16,
    zIndex: 2,
  },
  activityBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 215, 0, 0.3)",
  },
  activityBadgeEmoji: {
    fontSize: 18,
  },
  activityLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.platinum,
  },
  timeAgoBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  timeAgoText: {
    fontSize: 11,
    color: Colors.platinum,
    fontWeight: "600",
  },
  cardContent: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
  },
  userRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  userInfo: {
    flex: 1,
    marginRight: 12,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  userName: {
    fontSize: 24,
    fontWeight: "900",
    color: Colors.platinum,
  },
  ageBadge: {
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 215, 0, 0.3)",
  },
  ageText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.gold,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  metaText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.white,
  },
  metaDivider: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.smoke,
    opacity: 0.5,
    marginHorizontal: 4,
  },
  connectButton: {
    borderRadius: 16,
    overflow: "hidden",
  },
  connectGradient: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.gold,
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  connectText: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.bg,
  },
  requestedButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(57, 243, 255, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  requestedText: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.gold,
  },
  messagePreview: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  messageText: {
    flex: 1,
    fontSize: 13,
    color: Colors.platinum,
    fontStyle: "italic",
    lineHeight: 18,
  },
  bioSection: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  bioHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  bioLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.white,
    textTransform: "uppercase",
  },
  bioText: {
    fontSize: 13,
    color: Colors.white,
    lineHeight: 18,
  },
  expandIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
  },
  expandText: {
    fontSize: 12,
    color: Colors.white,
    fontWeight: "600",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 80,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.platinum,
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: Colors.smoke,
    textAlign: "center",
    paddingHorizontal: 40,
    marginBottom: 24,
  },
  resetButton: {
    backgroundColor: Colors.gold,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 16,
  },
  resetButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.bg,
  },
  endSpacer: {
    height: 40,
  },
});
