import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const GRID_SPACING = 8;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  feedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.platinum,
    letterSpacing: 0.5,
  },
  addMediaButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: "50%" as any,
    backgroundColor: Colors.bgSecondary,
    borderWidth: 1.2,
    borderStyle: "dashed",
    borderColor: Colors.gold,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: Colors.bgCard,
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: Colors.gold,
  },
  tabText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.smoke,
  },
  tabTextActive: {
    color: Colors.bg,
    fontWeight: "700",
  },
  feedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: GRID_SPACING,
  },
  feedItem: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
  },
  feedItemPressable: {
    flex: 1,
    position: "relative",
  },
  feedItemPressed: {
    opacity: 0.7,
  },
  feedItemImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  feedItemGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  videoIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -18 }, { translateY: -18 }],
  },
  durationBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  durationText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.platinum,
  },
  pinBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    transform: [{ rotate: "45deg" }],
  },
  multipleMediaBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  multipleMediaText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.platinum,
  },
  approvalBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    width: 28,
    height: 28,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: Colors.gold,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 6,
  },
  statusBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "rgba(251, 191, 36, 0.9)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusBadgeRejected: {
    backgroundColor: "rgba(239, 68, 68, 0.9)",
  },
  statusBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.bg,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  feedItemInfo: {
    position: "absolute",
    bottom: 0,
    left: 6,
    right: 0,
  },
  feedItemClub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  feedItemClubText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.platinum,
    flex: 1,
  },
  feedItemStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  feedStatText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.platinum,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyText: {
    color: Colors.platinum,
    fontSize: 16,
    fontWeight: "600",
    marginTop: 12,
  },
  emptySubtext: {
    color: Colors.smoke,
    fontSize: 13,
    marginTop: 4,
    textAlign: "center",
    paddingHorizontal: 32,
  },
  addPostBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: Colors.gold,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 14,
  },
  addPostBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.bg,
  },
});
