import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: 0,
    top: 4,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonContainer: {
    position: "absolute",
    bottom: 6,
    left: 0,
    right: 0,
    padding: 16,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.gold,
    paddingVertical: 14,
    borderRadius: 12,
  },
  saveButtonText: {
    color: Colors.bg,
    fontSize: 16,
    fontWeight: "700",
  },
  settingsButton: {
    position: "absolute",
    right: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.bgCard,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: 1.4,
    textAlign: "center",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 32,
  },
  loadingText: {
    fontSize: 16,
    color: Colors.lightGrey,
    fontWeight: "600",
  },
  notAuthText: {
    fontSize: 18,
    color: Colors.platinum,
    fontWeight: "600",
    marginTop: 16,
    textAlign: "center",
  },
  loginButton: {
    marginTop: 24,
    backgroundColor: Colors.gold,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 16,
  },
  loginButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.bg,
  },
  userInfoChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  userInfoText: {
    fontSize: 13,
    color: Colors.lightGrey,
    fontWeight: "500",
  },
  userRoleText: {
    fontSize: 13,
    color: Colors.gold,
    fontWeight: "600",
  },
  connectSection: {
    marginBottom: 24,
  },
  connectButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: Colors.gold,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  connectButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.bg,
  },
  connectButtonSent: {
    backgroundColor: "#10B981",
    opacity: 0.7,
  },
  chatNowButton: {
    backgroundColor: "#10B981",
  },
  chatNowButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  requestPendingButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: Colors.gold,
    borderStyle: "dashed",
  },
  requestPendingText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.gold,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
  },
  profilePictureSection: {
    alignItems: "center",
    marginBottom: 14,
    paddingVertical: 8,
  },
  avatarSection: {
    position: "relative",
    marginBottom: 16,
  },
  avatarRing: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: Colors.bgCard,
    borderWidth: 3,
    borderColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: -2,
    right: -16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: Colors.bg,
  },
  userName: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.platinum,
    letterSpacing: 0.5,
    marginBottom: 4,
    textAlign: "center",
  },
  userAge: {
    fontSize: 14,
    color: Colors.lightGrey,
    textAlign: "center",
  },
  tabSwitcher: {
    flexDirection: "row",
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 6,
    marginBottom: 24,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.15)",
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "transparent",
  },
  tabActive: {
    backgroundColor: Colors.gold,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.lightGrey,
  },
  tabTextActive: {
    color: Colors.bg,
  },
  bioEditContainer: {
    width: "100%",
    marginTop: 16,
  },
  bioInput: {
    backgroundColor: Colors.bgSecondary,
    borderRadius: 14,
    padding: 14,
    color: Colors.platinum,
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: "top",
    borderWidth: 2,
    borderStyle: "dotted",
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  bioText: {
    fontSize: 15,
    color: Colors.platinum,
    lineHeight: 22,
    marginTop: 16,
  },
  charCount: {
    fontSize: 11,
    color: Colors.lightGrey,
    textAlign: "right",
    marginTop: 6,
  },
  locationDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 16,
    padding: 12,
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    borderRadius: 12,
  },
  locationText: {
    flex: 1,
    fontSize: 14,
    color: Colors.platinum,
  },
  emptyText: {
    fontSize: 14,
    color: Colors.lightGrey,
    fontStyle: "italic",
    marginTop: 16,
    textAlign: "center",
  },
  section: {
    marginBottom: 32,
  },
  sectionCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.15)",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.platinum,
    letterSpacing: 0.5,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: Colors.lightGrey,
    marginBottom: 16,
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.bgSecondary,
    borderWidth: 2,
    borderStyle: "dotted",
    borderColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
  },
  drinksContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  drinkChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: Colors.bgSecondary,
  },
  drinkChipGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  drinkEmoji: {
    fontSize: 20,
  },
  drinkText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.platinum,
  },
  removeButton: {
    marginLeft: 4,
  },
  vibesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  vibeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.bgCard,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  vibeChipSelected: {
    backgroundColor: Colors.bgSecondary,
  },
  vibeEmoji: {
    fontSize: 18,
  },
  vibeText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.lightGrey,
  },
  vibeTextSelected: {
    color: Colors.platinum,
  },
  checkmark: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
  },
  clubsGrid: {
    gap: 16,
  },
  clubCard: {
    height: 160,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.15)",
  },
  clubCardImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  clubCardGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  clubCardContent: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  clubCardName: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.platinum,
    marginBottom: 4,
  },
  clubCardLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  clubCardLocationText: {
    fontSize: 13,
    color: Colors.white,
  },
  clubRemoveButton: {
    position: "absolute",
    top: 12,
    right: 12,
  },
  modalContent: {},
  clubModalContent: {},
  modalGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    margin: "auto",
    color: Colors.gold,
  },
  modalClose: {
    position: "absolute",
    right: 0,
    top: 0,
  },
  modalSubtitle: {
    fontSize: 13,
    color: Colors.lightGrey,
    marginBottom: 20,
  },
  modalInput: {
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    borderRadius: 14,
    padding: 14,
    color: Colors.platinum,
    fontSize: 15,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
    marginBottom: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    color: Colors.platinum,
    fontSize: 15,
  },
  clubsList: {
    flex: 1,
  },
  clubListItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "rgba(57, 243, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
    marginBottom: 10,
  },
  clubListItemSelected: {
    borderColor: Colors.gold,
    backgroundColor: "rgba(217, 175, 98, 0.1)",
  },
  clubListItemImage: {
    width: 60,
    height: 60,
    borderRadius: 10,
  },
  clubListItemContent: {
    flex: 1,
  },
  clubListItemName: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 4,
  },
  clubListItemLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  clubListItemLocationText: {
    fontSize: 12,
    color: Colors.lightGrey,
  },
  clubListItemCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  clubListItemCheckboxSelected: {
    backgroundColor: Colors.gold,
    borderColor: Colors.gold,
  },
  floatingButtonContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.bgCard,
    borderTopWidth: 1,
    borderTopColor: "rgba(217, 175, 98, 0.2)",
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.gold,
    paddingVertical: 14,
    borderRadius: 14,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.bg,
  },
  // Feed Styles
  feedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  addMediaButton: {
    padding: 4,
  },
  feedSubtitle: {
    fontSize: 13,
    color: Colors.lightGrey,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  feedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  feedItem: {
    width: "48%",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
  },
  feedItemPressable: {
    flex: 1,
    position: "relative",
  },
  feedItemImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  feedItemGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  videoIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -18 }, { translateY: -18 }],
  },
  durationBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  durationText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.platinum,
  },
  feedItemInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
  },
  feedItemClub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  feedItemClubText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.platinum,
    flex: 1,
  },
  feedItemStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  feedStatText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.platinum,
  },
  // Avatar Modal Styles
  avatarModalContent: {
    alignItems: "center",
    paddingVertical: 20,
  },
  avatarModalHeader: {
    flexDirection: "row",
    // alignItems: 'center',
    // justifyContent: 'space-between',
    width: "100%",
    marginBottom: 32,
    paddingHorizontal: 24,
  },
  avatarModalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.platinum,
    textAlign: "center",
    margin: "auto",
  },
  fullAvatarContainer: {
    width: 280,
    height: 280,
    borderRadius: 140,
    overflow: "hidden",
    marginBottom: 32,
    borderWidth: 4,
    borderColor: Colors.gold,
  },
  fullAvatar: {
    width: "100%",
    height: "100%",
  },
  fullAvatarPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarActionsContainer: {
    width: "100%",
    gap: 16,
    paddingHorizontal: 24,
  },
  avatarActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: Colors.primaryBlue,
    overflow: "hidden",
  },
  avatarActionGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  avatarActionText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.bg,
  },
  avatarRemoveButton: {
    borderColor: "rgba(255,69,58,0.2)",
    backgroundColor: Colors.bgCard,
  },
  avatarRemoveText: {
    color: "#ff3b30",
  },
  errorText: {
    fontSize: 16,
    color: Colors.smoke,
    textAlign: "center",
    marginTop: 16,
    marginBottom: 24,
  },
  errorButton: {
    backgroundColor: Colors.gold,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 12,
  },
  errorButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.bg,
  },
});
