import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/ui";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const TRIM_BAR_WIDTH = SCREEN_WIDTH - 64;
export const MAX_DURATION = 30.9;
export const HANDLE_WIDTH = 12;
export const HANDLE_HEIGHT = 60;
export const TIMELINE_HEIGHT = 6;
export const HANDLE_TOUCH_AREA = 44;

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 20,
  },
  content: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginBottom: 18,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.platinum,
    letterSpacing: 0.3,
  },
  doneButton: {
    position: "absolute",
    right: 0,
    top: 4,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: Colors.gold,
  },
  doneButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  doneButtonText: {
    color: Colors.bg,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  closebtn: {
    position: "absolute",
    left: 0,
    top: 6,
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.bgSecondary,
    gap: 8,
  },
  infoText: {
    fontSize: 12,
    color: Colors.platinum,
    fontWeight: "500",
    opacity: 0.9,
  },
  videoContainer: {
    aspectRatio: 9 / 16,
    backgroundColor: Colors.bgCard,
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 20,
    marginHorizontal: "auto",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  video: {
    flex: 1,
  },
  videoTapArea: {
    ...StyleSheet.absoluteFillObject,
  },
  trimmerVideoControls: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  trimmerPlayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  trimmerProgressContainer: {
    flex: 1,
    paddingVertical: 8,
    justifyContent: "center",
  },
  progressBar: {
    height: 3,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    position: "relative",
  },
  progressFill: {
    height: "100%",
    backgroundColor: Colors.gold,
  },
  progressThumb: {
    position: "absolute",
    top: -6.5,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.gold,
    marginLeft: -8,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#fff",
  },
  durationInfo: {
    flexDirection: "row",
    marginHorizontal: 6,
    marginBottom: 24,
    gap: 12,
  },
  durationChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  durationLabel: {
    fontSize: 11,
    color: Colors.smoke,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  durationValue: {
    fontSize: 14,
    color: Colors.gold,
    fontWeight: "700",
  },
  durationValueError: {
    color: "#ff6b6b",
  },
  trimSection: {
    paddingHorizontal: 22,
    marginBottom: 20,
  },
  trimContainer: {
    height: HANDLE_HEIGHT,
    position: "relative",
    marginBottom: 12,
  },
  timelineBackground: {
    position: "absolute",
    top: (HANDLE_HEIGHT - TIMELINE_HEIGHT) / 2,
    left: 0,
    right: 0,
    height: TIMELINE_HEIGHT,
    borderRadius: TIMELINE_HEIGHT / 2,
    overflow: "hidden",
  },
  timelineGradient: {
    flex: 1,
  },
  selectedRange: {
    position: "absolute",
    top: (HANDLE_HEIGHT - TIMELINE_HEIGHT) / 2,
    height: TIMELINE_HEIGHT,
    borderRadius: TIMELINE_HEIGHT / 2,
    overflow: "hidden",
  },
  selectedGradient: {
    flex: 1,
    backgroundColor: Colors.gold,
  },
  rangeBorderTop: {
    position: "absolute",
    top: -1,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: Colors.gold,
    opacity: 0.5,
  },
  rangeBorderBottom: {
    position: "absolute",
    bottom: -1,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: Colors.gold,
    opacity: 0.5,
  },
  handleTouchArea: {
    position: "absolute",
    top: -10,
    width: HANDLE_TOUCH_AREA,
    height: HANDLE_HEIGHT + 20,
    alignItems: "center",
    justifyContent: "center",
  },
  startHandleTouchArea: {
    left: -(HANDLE_TOUCH_AREA / 2),
  },
  endHandleTouchArea: {
    left: -(HANDLE_TOUCH_AREA / 2),
  },
  handle: {
    width: HANDLE_WIDTH,
    height: HANDLE_HEIGHT,
    borderRadius: HANDLE_WIDTH / 2,
    overflow: "hidden",
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 8,
  },
  startHandle: {
    // Positioning now handled by touch area
  },
  endHandle: {
    // Positioning now handled by touch area
  },
  handleGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.gold,
  },
  gripDots: {
    gap: 4,
    alignItems: "center",
  },
  gripDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: Colors.bg,
    opacity: 0.6,
  },
  handleGlow: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 20,
    backgroundColor: Colors.gold,
    opacity: 0.15,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  handleGlowLeft: {
    left: -10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  handleGlowRight: {
    right: -10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  currentTimeIndicator: {
    position: "absolute",
    top: (HANDLE_HEIGHT - TIMELINE_HEIGHT - 8) / 2,
    width: 2,
    height: TIMELINE_HEIGHT + 8,
    backgroundColor: Colors.primaryBlue,
    borderRadius: 1,
    shadowColor: Colors.primaryBlue,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
  },
  timelineLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  timelineLabel: {
    fontSize: 10,
    color: Colors.smoke,
    fontWeight: "500",
    opacity: 0.7,
  },
  timelineLabelCenter: {
    fontSize: 10,
    color: Colors.smoke,
    fontWeight: "500",
    opacity: 0.5,
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    marginHorizontal: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.3)",
  },
  warningText: {
    fontSize: 12,
    color: "#ff6b6b",
    fontWeight: "600",
  },
});
