import { Colors } from "@/constants/ui";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  appName: {
    fontSize: 28,
    fontWeight: "800",
    color: "#FF6B6B",
    letterSpacing: -0.5,
  },
  profileButton: {
    padding: 5,
  },
  headerTitles: {
    marginTop: 5,
  },
  nowText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#95A5A6",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  topClubsText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333",
    marginTop: 2,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    marginHorizontal: 20,
    marginTop: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  filtersContainer: {
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
  },
  filterButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    backgroundColor: "#FFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    marginRight: 10,
  },
  filterButtonActive: {
    backgroundColor: "#FF6B6B",
    borderColor: "#FF6B6B",
  },
  filterText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#95A5A6",
  },
  filterTextActive: {
    color: "#FFF",
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  clubCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  clubHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  rankContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FF6B6B",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  rankNumber: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFF",
  },
  clubInfo: {
    flex: 1,
  },
  clubNameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  clubName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
    flex: 1,
    marginRight: 10,
  },
  tagDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  tagContainer: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 10,
  },
  tagText: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  distanceContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  distanceText: {
    fontSize: 13,
    color: "#95A5A6",
    marginLeft: 4,
    fontWeight: "500",
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4CAF50",
    marginRight: 8,
  },
  statusText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  vibeScoreContainer: {
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
  },
  vibeScoreLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#95A5A6",
    marginRight: 10,
    textTransform: "uppercase",
  },
  vibeScoreBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#E0E0E0",
    borderRadius: 4,
    overflow: "hidden",
    marginRight: 10,
  },
  vibeScoreFill: {
    height: "100%",
    borderRadius: 4,
  },
  vibeScoreValue: {
    fontSize: 16,
    fontWeight: "700",
    minWidth: 30,
    textAlign: "right",
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 5,
  },
  navText: {
    fontSize: 12,
    color: "#95A5A6",
    marginTop: 4,
  },
  navTextActive: {
    fontSize: 12,
    color: "#FF6B6B",
    marginTop: 4,
    fontWeight: "600",
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#95A5A6",
    marginTop: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "90%",
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333",
    flex: 1,
  },
  closeButton: {
    padding: 4,
  },
  modalSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  modalTagRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  modalTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 10,
  },
  modalTagText: {
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  modalInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
  },
  modalInfoText: {
    fontSize: 14,
    color: "#333",
    marginLeft: 4,
    fontWeight: "500",
  },
  modalSectionTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#95A5A6",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  modalStatus: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  modalVibeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  modalVibeBar: {
    flex: 1,
    height: 12,
    backgroundColor: "#E0E0E0",
    borderRadius: 6,
    overflow: "hidden",
    marginRight: 15,
  },
  modalVibeFill: {
    height: "100%",
    borderRadius: 6,
  },
  modalVibeScore: {
    fontSize: 18,
    fontWeight: "700",
    minWidth: 70,
  },
  modalDescription: {
    fontSize: 16,
    color: "#333",
    lineHeight: 24,
    marginBottom: 20,
  },
  detailsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  detailItem: {
    width: "48%",
    backgroundColor: "#F8F9FA",
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
  },
  detailLabel: {
    fontSize: 12,
    color: "#95A5A6",
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
  },
  modalButtons: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF6B6B",
    paddingVertical: 15,
    borderRadius: 12,
    marginRight: 10,
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#FF6B6B",
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFF",
    marginLeft: 8,
  },
  clubsEndText: {
    textAlign: "center",
    fontSize: 13,
    color: Colors.smoke,
    fontWeight: "500",
    paddingVertical: 24,
  },
});
