version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: zonke-clubs-localstack
    ports:
      - "4566:4566" # LocalStack gateway
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PERSISTENCE=1
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - zonke-network

networks:
  zonke-network:
    driver: bridge

volumes:
  localstack-data:
