import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    position: "relative",
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  badge: {
    position: "absolute",
    right: 20,
    top: 20,
    backgroundColor: Colors.gold,
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.bg,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  emptyContentContainer: {
    flex: 1,
  },
  threadCard: {
    marginBottom: 12,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.12)",
  },
  threadGradient: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bgCard,
    padding: 14,
    gap: 12,
  },
  threadDisconnected: {
    opacity: 0.7,
    borderColor: "rgba(239, 68, 68, 0.2)",
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.velvet,
  },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.velvet,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitial: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.platinum,
  },
  onlineBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#10B981",
    borderWidth: 2,
    borderColor: Colors.bg,
  },
  unreadIndicator: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: Colors.gold,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: Colors.bg,
  },
  unreadCount: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.bg,
  },
  disconnectedBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: Colors.bg,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.bg,
  },
  threadContent: {
    flex: 1,
    justifyContent: "center",
  },
  threadHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  participantName: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.platinum,
  },
  unreadText: {
    fontWeight: "700",
  },
  timeText: {
    fontSize: 12,
    color: Colors.smoke,
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  checkIcon: {
    marginRight: 2,
  },
  lastMessage: {
    flex: 1,
    fontSize: 14,
    color: Colors.smoke,
    lineHeight: 18,
  },
  disconnectedText: {
    color: Colors.smoke,
    opacity: 0.7,
  },
  disconnectedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  disconnectedMessage: {
    fontSize: 14,
    color: Colors.smoke,
    fontStyle: "italic",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(57, 243, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 12,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: Colors.smoke,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 32,
  },
  exploreButton: {
    flexDirection: "row",
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 8,
    backgroundColor: Colors.gold,
    overflow: "hidden",
  },
  exploreGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  exploreText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.bg,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
  },
  loadingText: {
    fontSize: 15,
    color: Colors.smoke,
  },
});
