import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.gold,
    letterSpacing: 0.5,
    marginBottom: 20,
    textTransform: "uppercase",
  },
  contentSection: {
    width: "100%",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: "50%",
    backgroundColor: Colors.bgSecondary,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Colors.gold,
  },
  addButtonText: {
    color: Colors.gold,
    fontSize: 14,
    fontWeight: "700",
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: Colors.bgSecondary,
    borderRadius: 16,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  tabActive: {
    backgroundColor: Colors.gold,
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.smoke,
  },
  tabTextActive: {
    color: Colors.bg,
    fontWeight: "700",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  gridItem: {
    aspectRatio: 1,
  },
  gridItemPressable: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
  },
  gridItemPressed: {
    opacity: 0.7,
  },
  gridImage: {
    width: "100%",
    height: "100%",
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    // backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  videoIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -15 }, { translateY: -15 }],
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  durationBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationText: {
    color: Colors.platinum,
    fontSize: 10,
    fontWeight: "700",
  },
  likeBadge: {
    position: "absolute",
    bottom: 4,
    left: 4,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  likeText: {
    color: Colors.platinum,
    fontSize: 10,
    fontWeight: "700",
  },
  gradientOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "30%",
    backgroundColor: "transparent",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 48,
    backgroundColor: "rgba(57, 243, 255, 0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  emptyText: {
    color: Colors.smoke,
    fontSize: 14,
    marginTop: 12,
  },
  viewAllContainer: {
    marginTop: 12,
  },
  viewAllButton: {
    backgroundColor: "rgba(57, 243, 255, 0.08)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  viewAllContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  viewAllLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  viewAllText: {
    color: Colors.platinum,
    fontSize: 15,
    fontWeight: "700",
  },
});
