import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/ui";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    // Modal component handles container styling
  },
  headerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 100,
  },
  header: {
    flexDirection: "row",
    // alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    // paddingTop: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.gold,
    letterSpacing: 0.5,
  },
  closeBtn: {
    position: "absolute",
    left: 0,
    // top: 6
  },
  postButton: {
    position: "absolute",
    right: 0,
    // top: 8,
    backgroundColor: Colors.gold,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  postButtonDisabled: {
    opacity: 0.5,
  },
  postButtonText: {
    color: Colors.bg,
    fontSize: 15,
    fontWeight: "700",
  },
  content: {
    paddingHorizontal: 16,
  },
  tagClubSection: {
    marginBottom: 24,
  },
  tagHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  tagHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tagHeaderTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.platinum,
    letterSpacing: 0.5,
  },
  selectedClubBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(57, 243, 255, 0.08)",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Colors.gold,
  },
  selectedClubBarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Colors.gold,
  },
  selectedClubBarInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 12,
    gap: 6,
  },
  selectedClubBarHash: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.gold,
  },
  selectedClubBarName: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.platinum,
  },
  removeClubButton: {
    padding: 4,
  },
  selectedClubPillRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  selectedClubPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.bgSecondary,
    borderWidth: 1,
    borderColor: Colors.gold,
    borderRadius: 20,
    paddingVertical: 5,
    paddingLeft: 10,
    paddingRight: 6,
    alignSelf: "flex-start",
    maxWidth: "80%",
  },
  selectedClubPillHash: {
    fontSize: 13,
    fontWeight: "900",
    color: Colors.gold,
  },
  selectedClubPillName: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.platinum,
    flexShrink: 1,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.2)",
    gap: 10,
  },
  searchIcon: {
    opacity: 0.7,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: Colors.platinum,
    padding: 0,
  },
  suggestionsContainer: {
    marginTop: 8,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.2)",
    overflow: "hidden",
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57, 243, 255, 0.1)",
  },
  suggestionImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.gold,
  },
  suggestionInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 12,
    gap: 6,
  },
  suggestionHash: {
    fontSize: 14,
    fontWeight: "900",
    color: Colors.gold,
  },
  suggestionName: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.platinum,
  },
  noResultsContainer: {
    marginTop: 8,
    padding: 16,
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  noResultsText: {
    fontSize: 13,
    color: Colors.smoke,
    textAlign: "center",
    fontStyle: "italic",
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  actionsSection: {
    marginBottom: 24,
  },
  actionsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  actionButtonGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.platinum,
    marginTop: 8,
    textAlign: "center",
  },
  mediaSection: {
    marginBottom: 24,
  },
  mediaSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  addMoreHint: {
    fontSize: 11,
    color: Colors.smoke,
    fontStyle: "italic",
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mediaItem: {
    width: (SCREEN_WIDTH - 48) / 3,
    height: (SCREEN_WIDTH - 48) / 3,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
  },
  mediaItemImage: {
    width: "100%",
    height: "100%",
  },
  videoContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  durationBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  durationText: {
    fontSize: 10,
    color: Colors.platinum,
    fontWeight: "600",
  },
  removeButton: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    overflow: "hidden",
  },
  removeButtonBlur: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  descriptionSection: {
    marginBottom: 24,
  },
  descriptionInput: {
    backgroundColor: Colors.bgCard,
    borderRadius: 14,
    padding: 14,
    color: Colors.platinum,
    fontSize: 15,
    minHeight: 100,
    textAlignVertical: "top",
    borderWidth: 2,
    borderColor: "rgba(57, 243, 255, 0.2)",
  },
  charCount: {
    fontSize: 11,
    color: Colors.smoke,
    textAlign: "right",
    marginTop: 6,
  },
  processingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
  },
  processingContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  processingIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: "hidden",
    marginBottom: 20,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  processingIconGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  processingTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.platinum,
    marginBottom: 8,
    textAlign: "center",
  },
  processingSubtitle: {
    fontSize: 14,
    color: Colors.smoke,
    marginBottom: 32,
    textAlign: "center",
  },
  progressBarContainer: {
    width: "100%",
    alignItems: "center",
    gap: 12,
  },
  progressBarBackground: {
    width: "100%",
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: Colors.gold,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.gold,
  },
  previewContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  previewTopBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  previewCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
  },
  previewMediaContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  previewVideo: {
    width: "100%",
    height: "100%",
  },
  previewVideoTapArea: {
    ...StyleSheet.absoluteFillObject,
  },
  previewBottomControls: {
    position: "absolute",
    bottom: 50,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  previewPlayPauseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  previewProgressContainer: {
    flex: 1,
    paddingVertical: 8,
    justifyContent: "center",
  },
  previewProgressBar: {
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 2,
    position: "relative",
  },
  previewProgressFill: {
    height: "100%",
    backgroundColor: Colors.gold,
  },
  previewProgressThumb: {
    position: "absolute",
    top: -6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.gold,
    marginLeft: -8,
    shadowColor: Colors.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#fff",
  },
  previewMuteButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  gestureRoot: {
    flex: 1,
    backgroundColor: "#000",
  },
});
