import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  card: {
    flexDirection: "column",
    width: 160,
    height: 250,
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 16,
    paddingTop: 12,
    paddingBottom: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.1)",
  },
  dateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(57, 243, 255, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    marginBottom: 10,
  },
  dateText: {
    color: Colors.gold,
    fontSize: 11,
    fontWeight: "700",
  },
  avatarContainer: {
    marginBottom: 10,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.velvet,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 28,
    backgroundColor: Colors.smoke,
  },
  avatarInitial: {
    color: Colors.platinum,
    fontSize: 22,
    fontWeight: "700",
  },
  name: {
    color: Colors.platinum,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
  },
  emoji: {
    fontSize: 14,
  },
  activityText: {
    color: Colors.smoke,
    fontSize: 12,
    fontWeight: "600",
  },
  message: {
    color: Colors.smoke,
    fontSize: 11,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 16,
  },
  connectButton: {
    position: "absolute",
    bottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: Colors.gold,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginTop: 12,
    width: "100%",
  },
  connectText: {
    color: Colors.bg,
    fontSize: 13,
    fontWeight: "700",
  },
  chatButton: {
    position: "absolute",
    bottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: Colors.gold,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginTop: 12,
    width: "100%",
  },
  chatText: {
    color: Colors.bg,
    fontSize: 13,
    fontWeight: "700",
  },
  youBadge: {
    backgroundColor: "rgba(57, 243, 255, 0.15)",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginTop: 12,
  },
  youText: {
    color: Colors.gold,
    fontSize: 12,
    fontWeight: "600",
  },
  requestedBadge: {
    position: "absolute",
    bottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(57, 243, 255, 0.15)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginTop: 12,
    width: "100%",
    borderWidth: 1,
    borderColor: "rgba(57, 243, 255, 0.3)",
  },
  requestedIconContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  requestedText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: "700",
  },
});
